### ISSUE TITLE
Existing Node DB

### ISSUE THREAD

**Issue by djekl** [868meshbot/meshbot#3]
Hey,

Instead of pulling the NodeDB info from sites like the Mpowered247 Map html source, and compiling an SQLite DB from it, why not just use the Meshtastic API and pull it from there directly?

https://api.meshtastic.org/mqtt/

**Comment by djekl** [comment]
Looking at the data, you could only really use it for map positions. Closing…

**Comment by hayschan** [comment]
What about the [meshmap.net](https://meshmap.net/) site ? 

@djekl
